# Generated by Django 5.0.1 on 2024-01-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="address_two",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="financial_goals",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="industry",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="life_goals",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("widowed", "Widowed"),
                    ("divorced", "Divorced"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="number_of_children",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="salary",
            field=models.IntegerField(null=True),
        ),
    ]
