# Generated by Django 5.0.1 on 2024-01-20 01:18

import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_useraddress_address_two_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="address_one",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="city",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="state",
            field=localflavor.us.models.USStateField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="zipcode",
            field=models.IntegerField(null=True),
        ),
    ]
