# Generated by Django 5.0.1 on 2024-01-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0004_alter_useraddress_address_one_alter_useraddress_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="address_two",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
